#!/usr/bin/env php
<?php

$arguments = $argv;
array_shift($arguments);

$ds = DIRECTORY_SEPARATOR;

// Check if selenium server is already running.
$selenium = @fsockopen('localhost', 4444);
if ($selenium !== false) {
    fclose($selenium);
}
else {
    $path    = str_replace('/', $ds, 'tests/behat/drivers/');
    $log     = str_replace('/', $ds, 'tests/behat/logs/selenium.log');
    $server  = 'selenium-server-standalone-3.141.59.jar';
    $drivers = " -Dwebdriver.gecko.driver={$path}geckodriver -Dwebdriver.chrome.driver={$path}chromedriver";

    if ($ds == '/') {
        // Firefox|Chrome Linux
        shell_exec("java -jar $drivers {$path}{$server} -log {$log} > /dev/null 2>&1 &");
    } else {
        // Firefox|Chrome Windows
        pclose(popen("start /B  java -jar {$drivers}.exe {$path}{$server} -log {$log}", 'r'));
    }
    // Make sure selenium is running.
    sleep(1);
}

system(str_replace('/', $ds, 'vendor/bin/behat --colors ' ) . implode(' ', $arguments));
